name: Auto-Merge

on: pull_request

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    # Specifically check that dependabot (or another trusted party) created this pull-request.
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - uses: alexwilson/enable-github-automerge-action@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
